#ifndef API_UNICODE_H
#define API_UNICODE_H

// API exposed by the implementation
#include "../../src/unicode/api.h"

// Unicode categories
#define UNICODE_CATEGORY_CN __UNICODE_CATEGORY_CN
#define UNICODE_CATEGORY_LU __UNICODE_CATEGORY_LU
#define UNICODE_CATEGORY_LL __UNICODE_CATEGORY_LL
#define UNICODE_CATEGORY_LT __UNICODE_CATEGORY_LT
#define UNICODE_CATEGORY_LM __UNICODE_CATEGORY_LM
#define UNICODE_CATEGORY_LO __UNICODE_CATEGORY_LO
#define UNICODE_CATEGORY_MN __UNICODE_CATEGORY_MN
#define UNICODE_CATEGORY_MC __UNICODE_CATEGORY_MC
#define UNICODE_CATEGORY_ME __UNICODE_CATEGORY_ME
#define UNICODE_CATEGORY_ND __UNICODE_CATEGORY_ND
#define UNICODE_CATEGORY_NL __UNICODE_CATEGORY_NL
#define UNICODE_CATEGORY_NO __UNICODE_CATEGORY_NO
#define UNICODE_CATEGORY_PC __UNICODE_CATEGORY_PC
#define UNICODE_CATEGORY_PD __UNICODE_CATEGORY_PD
#define UNICODE_CATEGORY_PS __UNICODE_CATEGORY_PS
#define UNICODE_CATEGORY_PE __UNICODE_CATEGORY_PE
#define UNICODE_CATEGORY_PI __UNICODE_CATEGORY_PI
#define UNICODE_CATEGORY_PF __UNICODE_CATEGORY_PF
#define UNICODE_CATEGORY_PO __UNICODE_CATEGORY_PO
#define UNICODE_CATEGORY_SM __UNICODE_CATEGORY_SM
#define UNICODE_CATEGORY_SC __UNICODE_CATEGORY_SC
#define UNICODE_CATEGORY_SK __UNICODE_CATEGORY_SK
#define UNICODE_CATEGORY_SO __UNICODE_CATEGORY_SO
#define UNICODE_CATEGORY_ZS __UNICODE_CATEGORY_ZS
#define UNICODE_CATEGORY_ZL __UNICODE_CATEGORY_ZL
#define UNICODE_CATEGORY_ZP __UNICODE_CATEGORY_ZP
#define UNICODE_CATEGORY_CC __UNICODE_CATEGORY_CC
#define UNICODE_CATEGORY_CF __UNICODE_CATEGORY_CF
#define UNICODE_CATEGORY_CS __UNICODE_CATEGORY_CS
#define UNICODE_CATEGORY_CO __UNICODE_CATEGORY_CO

// Functions
#define READ_CP(uc) read_codepoint(uc)
#define BACKUP_CP(uc) backup_codepoint(uc)
#define UNICODE_INIT(uc) unicode_init(uc)
#define UNICODE_CAT(cp) unicode_cat(cp)
#define UNICODE_TO_ENCODING(cps, cp_len, out, len) unicode_to_encoding(cps, cp_len, out, len)
#define CP_WIDTH(cp) codepoint_width(cp)

#endif